[package]
name = "riscv_trace_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = "1.1.0"
regex = "1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
anyhow = "1.0.98"

[lib]
name = "riscv_trace_reader"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
